routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'PageController@show');

// Route::get('/legal', 'PageController@legal');
// Route::get('/faq', 'PageController@faq');
// Route::get('/help', 'PageController@help');
// Route::get('/terms', 'PageController@terms');
// Route::get('/contact', 'PageController@contact');
// Route::get('/privacy', 'PageController@privacy');
// Route::get('/gallery', 'PageController@gallery');

Route::post('register', 'RegisterController@store');

// Route::get('email', function () {
//     return view('emails.successful_registration');
// });

// Route::get('/article', 'ArticleController@index');
// Route::get('/article/{id}', 'ArticleController@show');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use League\CommonMark\CommonMarkConverter;
use Carbon\Carbon;

class Article extends Model
{
	protected $dates = ['published_at'];

	protected function markdown()
	{
		$converter = new CommonMarkConverter();
		return $converter;
	}

	public function getPublishedAtAttribute()
    {
        $date = date_create($this->attributes['published_at']);
        return $this->attributes['published_at'] = date_format($date, 'd-m-Y');
    }

	public function getPublishedAtLocalizedAttribute()
    {
        setlocale(LC_TIME, 'id_ID.UTF-8');
        return Carbon::parse($this->attributes['published_at'])->formatLocalized('%d %B %Y');
    }

	public function getBodyHtmlAttribute()
	{
		return $this->attributes['body'] = $this->markdown()->convertToHtml($this->attributes['body']);
	}

	public function getExcerptHtmlAttribute()
	{
		
		return $this->attributes['excerpt'] = $this->markdown()->convertToHtml($this->attributes['excerpt']);
	}
}

app/Models/FaqTranslation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use League\CommonMark\CommonMarkConverter;

class FaqTranslation extends Model
{
    protected $table = 'faqs_translation';

    protected function markdown()
	{
		$converter = new CommonMarkConverter();
		return $converter;
	}

    public function getAnswerHtmlAttribute()
	{
		return $this->attributes['answer'] = $this->markdown()->convertToHtml($this->attributes['answer']);
	}
}

app/Models/Page.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use League\CommonMark\CommonMarkConverter;
use Baum\Node;

class Page extends Node
{
    protected function markdown()
	{
		$converter = new CommonMarkConverter();
		return $converter;
	}
	
	public function getContentHtmlAttribute()
	{
		return $this->attributes['content'] = $this->markdown()->convertToHtml($this->attributes['content']);
	}
}

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use League\CommonMark\CommonMarkConverter;
use Carbon\Carbon;

class Video extends Model
{
    protected $dates = ['published_at'];

    protected function markdown()
	{
		$converter = new CommonMarkConverter();
		return $converter;
	}

    public function getDescriptionHtmlAttribute()
	{
		return $this->attributes['description'] = $this->markdown()->convertToHtml($this->attributes['description']);
	}

    public function getPublishedAtAttribute()
    {
        $date = date_create($this->attributes['published_at']);
        return $this->attributes['published_at'] = date_format($date, 'd-m-Y');
    }

    public function getPublishedAtDiffAttribute()
    {
        return $this->attributes['published_at'] = Carbon::createFromFormat('Y-m-d H:i:s', $this->attributes['published_at'])->diffForHumans();
    }

    public function getPublishedAtLocalizedAttribute()
    {
        setlocale(LC_TIME, 'id_ID.UTF-8');
        return Carbon::parse($this->attributes['published_at'])->formatLocalized('%d %B %Y');
    }
}

resources/views/templates/about.blade.php
  <section id="about">
    <!-- BEGIN CONTENT 1-->
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="section-heading">Tentang Kami</h2>
                <hr class="primary">
            </div>
        </div>
        <!-- Begin Content -->      
        <div class="col-md-4 page-1">
        <a href="#"><img src="img/nurse1.png" alt="" class="img-nurse"></a>
        </div>

        <div class="col-md-8 p-right">
        <h4>APA ITU <br> RAWAT SEHAT?</h4>

        <hr class="head-line pull-left"><br><br>

        {!! $pages->content_html !!}
        </div>
    </div>
    <!-- END CONTENT 1 -->
  </section>

  {{-- <!-- BEGIN CONTENT 2 -->
  <div class="main-banner"></div>
    <div class="container page-2">
      <div class="col-md-offset-2 col-md-5">
      <h4> RAWAT SEHAT APPS</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>

      <div class="col-md-10 store">
      <center><h5>DOWNLOAD DI:</h5></center>
      <a href="#"><img src="img/appstore.png" class="text-left iconStore" alt=""></a>
      <a href="#"><img src="img/googleplay.png" class="text-right iconStore" alt=""></a>
      </div>
      </div>

      <div class="col-md-5 apps">
        <a href="#"><img src="img/apps.png" alt="" class="img-apps"></a>
      </div>
    </div>
    <!-- END CONTENT 2 --> --}}

resources/views/templates/articles.blade.php
<section id="articles">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="section-heading">Artikel</h2>
                <hr class="primary">
            </div>
        </div>

        <div class="row">
            <div id="article-mansonry" class="article-list">  
                @foreach ($articles as $article)
                   <article class="post col-md-4 col-sm-6 col-xs-12" >
                        <div class="post-inner">
                            <figure class="post-thumb">
                                <a href="{{ route('article.post', [$article->slug]) }}">
                                    @if($article->thumbnail_path)
                                        <img class="img-responsive" src="http://api.server.rawatsehat.net/{{ $article->thumbnail_path }}" alt="">
                                    @else
                                        <img class="img-responsive hidden-xs" src="http://www.placehold.it/360x240/253340/ffffff?text=no+image">
                                    @endif
                                    {{-- <img class="img-responsive" src="assets/images/blog/post-1-thumb.jpg" alt="" /> --}}
                                </a>                                
                            </figure><!--//post-thumb-->
                            <div class="content">
                                <h3 class="post-title"><a href="{{ route('article.post', [$article->slug]) }}" title="{{ $article->title }}">{{ str_limit($article->title, 40) }}</a></h3>
                                <div class="post-entry">
                                    <p>{!! str_limit($article->body_html, 200) !!}</p>
                                    <a class="read-more" href="{{ route('article.post', [$article->slug]) }}">Read more <i class="fa fa-long-arrow-right"></i></a>
                                </div>
                                <div class="meta">
                                    <ul class="meta-list list-inline">                                       
                                    	<li class="post-time post_date date updated">{{ $article->published_at }}</li>
                                    	<li class="post-author"> by <a href="{{ route('article.post', [$article->slug]) }}">{!! $article->author !!}</a></li>
                                    	<li class="post-comments-link">
                                	        <a href="#"><i class="fa fa-comments"></i>8</a>
                                	    </li>
                                	</ul><!--//meta-list-->                           	
                                </div><!--meta-->
                            </div><!--//content-->
                        </div><!--//post-inner-->
                    </article><!--//post-->
                @endforeach
            </div>
        </div>

        <!-- PAGINATION -->
        <div class="row">
            <div class="pagination-container text-center">
                {{ $articles->links() }}
            </div>
        </div>
        <!-- PAGINATION -->

        </div>  
    </div>
</section>

resources/views/templates/contact.blade.php
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="section-heading">
                    Kontak
                </h2>
                <hr class="primary">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <p>
                    <b>Jl. Mojo Kidul 52A</b></br>
                    Surabaya 60232, Indonesia</br></br>
                    Email: info@rawatsehat.com</br>
                    Phone: 082141070700</br>
                    {{-- Website: www.rawatsehat.com</br>
                    Facebook: Rawat Sehat</br>
                    Twitter: @rawat_sehat</br>
                    Instagram: rawatsehat --}}
                </p>
                <div style="height:350px;width:100%;max-width:100%;list-style:none; transition: none;overflow:hidden;"><div id="my-map-canvas" style="height:100%; width:100%;max-width:100%;"><iframe style="height:100%;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/search?q=Jalan+Mojo+Kidul+52A&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe></div><a class="google-map-code" href="http://www.szablonypremium.pl" id="enable-map-data">http://www.szablonypremium.pl</a><style>#my-map-canvas .text-marker{max-width:none!important;background:none!important;}img{max-width:none}</style></div>
            </div>
            <div class="col-md-6">
                <form action="">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" placeholder="Name">
                    </div>
                    
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                    </div>

                    <div class="form-group">
                        <label for="message">Message</label>
                        <textarea name="message" class="form-control" id="message" rows="5" placeholder="Message"></textarea>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-10 col-sm-2">
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

resources/views/templates/faq.blade.php
<section id="legal_info">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="section-heading">
                    F.A.Q
                </h2>
                <hr class="primary">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul id="toggle-view">
                    @foreach ($translations as $translation)     
                        <li class="faq-content">
                            <p class="faq-title">{!! $translation->question !!}</p>
                            <span>+</span>
                            <div class="collapse">
                                {!! $translation->answer_html !!}
                            </div>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
</section>

resources/views/templates/home.blade.php
<section class="slider">
    <div class="flexslider img-slider">
        <ul class="slides">
            <li class="slide">
                <img src="img/banner-registrasi-02.jpg" />
            </li>
            <li class="slide">
  	    	    <img src="img/slide_web-01.jpg"/>
            </li>
            <li class="slide">
  	    	    <img src="img/slider1.jpg"/>
            </li>
        </ul>
    </div>
</section>

<div class="container bg-white">
    <img src="img/alur_registrasi_rawat_sehat.png" class="img-responsive"/>
    <hr>
</div>

<!-- BEGIN CONTENT 1-->
<div class="container">
    <!-- Begin Content -->      
    <div class="col-md-4 page-1">
        <a href="#"><img src="img/nurse1.png" alt="" class="img-nurse"></a>
    </div>

    <div class="col-md-8 p-right">
        <h4>APA ITU <br> RAWAT SEHAT ?</h4>

        <hr class="head-line pull-left"><br><br>

        <p>{!! str_limit($about->content_html, 250) !!}</p>
        </br>
        <a href="/about" class="btn-more btn"> Read More</a>
    </div>
</div>
<!-- END CONTENT 1 -->

<!-- BEGIN CONTENT 2 -->
<div class="main-banner"></div>
    <div class="container page-2">
        <div class="col-md-offset-2 col-md-5">
        <h4> RAWAT SEHAT APPS</h4>
        {!! $pages->content_html !!}

        <div class="col-md-12 store">
            <center><h5>DOWNLOAD DI:</h5></center>
            <a href="https://goo.gl/A1N0AL" target="_blank"><img src="img/appstore.png" class="text-left iconStore" alt=""></a>
            <a href="https://goo.gl/A1N0AL" target="_blank"><img src="img/googleplay.png" class="text-right iconStore" alt=""></a>
        </div>
    </div>

    <div class="col-md-5 apps">
        <a href="#"><img src="img/apps.png" alt="" class="img-apps"></a>
    </div>
</div>
<!-- END CONTENT 2 -->

<!-- BEGIN CONTENT 3 -->
<div class="list-video">
    <div class="container video-post text-center">
        <center><h3><b>VIDEO</b></h3></center>
        <hr class="head-line-1">
        <iframe  id="vid_frame" class="vid_frame" src="http://youtube.com/embed/WJL-v4Yg0lw?autoplay=0&rel=0&showinfo=0" frameborder="0" width="70%" height="400"></iframe>
        <br><br>
    </div> 
</div>
<!-- END CONTENT 3 -->

<!-- BEGIN CONTENT 4 -->
{{-- <div  id="quotes-section" class="row">                                
    <div id="myCarousel2" class="carousel slide col-md-12" data-ride="carousel"> 
        <h2>Kata Mereka</h2>
        <ol class="carousel-indicators show">
            <li data-target="#myCarouse2" data-slide-to="0" class="active"></li>
            <li data-target="#myCarouse2" data-slide-to="1"></li>
        </ol>

        <div class="carousel-inner" role="listbox">
            <div class="item active row">
                <div class="col-md-offset-2 col-md-2">
                <img src="img/photo.png">
                </div>
                <div class="col-md-8 quotes">
                <blockquote>
                    <i class="fa fa-quote-left"></i>
                    <p>" Layanan ini sangat membantu untuk menambah panghasilan bagi saya "</p>
                    <p><b> Dr Casey Kasianto, Dokter Spesialis paru</b></p>
                </blockquote> 
                </div>
            </div>

            <div class="item row">
                <div class="col-md-offset-2 col-md-2">
                <img src="img/photo.png">
                </div>
                <div class="col-md-8 quotes">
                <p>Rawat sehat sangat membantu saya dalam merawat ibu saya</p>
                <p><b> Muhammad Ali, pasien</b></p>
                </div>
            </div>
        </div>
    </div>
</div> --}}

<section class="section testimonials">
    <div class="container">
        <h2 class="title text-center">Kata Mereka</h2>
        <hr class="primary">
        <div id="testimonials-carousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators show">
                @foreach ($testimonials as $i => $testimonial)
                    <li data-target="#testimonials-carousel" data-slide-to="{{$i}}" class="{{ $i == 0 ? 'active' : '' }}"></li>
                @endforeach
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox"> 
                @foreach ($testimonials as $i => $testimonial)
                    <div class="item {{ $i == 0 ? 'active' : '' }}">
                        <figure class="profile"><img src="img/photo.png" alt="" /></figure>
                        <div class="content">
                            <blockquote>
                            <i class="fa fa-quote-left"></i>
                            {!! $testimonial->review !!}
                            </blockquote>
                            <p class="source">{!! $testimonial->author !!}<br /><span class="title">{!! $testimonial->designation !!}</span></p>
                        </div><!--//content-->                         
                    </div><!--//item-->
                @endforeach
            </div>
        </div>
    </div>
</section>
<!-- END CONTENT 4 -->

resources/views/templates/register.blade.php
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="section-heading">
                    Formulir Pendaftaran Online
                </h2>
                <hr class="primary">
            </div>
        </div>
        <div class="row">
            <div class="col-md-offset-1 col-md-10">
                @include('flash::message')
                @include('errors.list')
                @include('templates.partials._formRegister')
                <blockquote>
                    <dl>
                        <dt>Syarat dan Ketentuan:</dt>
                        <dd>
                            <ul>
                                <li>Memiliki smartphone dengan sistem <b>android</b> atau <b>IOS</b></li>
                                <li>No. <b>STR</b> ( Surat Tanda Registrasi )</li>
                                <li>No. <b>SIP</b> ( Surat Ijin Praktek )</li>
                            </ul>
                        </dd>
                    </dl>
                </blockquote>
            </div>
        </div>
    </div>
</section>

resources/views/templates/services.blade.php
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="section-heading">Layanan Kami</h2>
                <hr class="primary">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @foreach ($services as $service)     
                    <div class="col-md-4">
                        <div class="service-item">
                            <img src="http://api.server.rawatsehat.net/{{ $service->path_logo }}" class="img-responsive" alt="">
                            <h3>{{ $service->name }}</h3>
                            {!! $service->description_html !!}
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</section>

resources/views/templates/videos.blade.php
<section id="articles">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="section-heading">Video</h2>
                <hr class="primary">
            </div>
        </div>

        <div class="row">
            <div id="video-mansonry" class="article-list">  
                @foreach ($videos as $video)
                   <article class="post col-md-4 col-sm-6 col-xs-12">
                        <div class="post-inner">
                            <figure class="post-thumb">
                                <a href="{{ route('video.post', [$video->slug]) }}">
                                     <img class="img-responsive" src="https://img.youtube.com/vi/{{ substr($video->src, 32) }}/mqdefault.jpg">
                                    {{-- @if($video->thumbnail_path)
                                        <img class="img-responsive hidden-xs" src="http://api.server.rawatsehat.net/{{ $video->thumbnail_path }}" alt="">
                                    @else
                                        <img class="img-responsive hidden-xs" src="http://www.placehold.it/360x240/253340/ffffff?text=no+image">
                                    @endif --}}
                                    {{-- <img class="img-responsive" src="assets/images/blog/post-1-thumb.jpg" alt="" /> --}}
                                </a>                                
                            </figure><!--//post-thumb-->
                            <div class="content">
                                <h3 class="post-title"><a href="{{ route('video.post', [$video->slug]) }}" title="{{ $video->title }}">{{ str_limit($video->title, 50) }}</a></h3>
                                <div class="post-entry">
                                    <p>{!! str_limit($video->body_html, 120) !!}</p>
                                </div>
                                <div class="meta">
                                    <ul class="meta-list list-inline">                                       
                                    	<li class="post-time post_date date updated">{{ $video->published_at_diff }}</li>
                                	</ul><!--//meta-list-->
                                </div><!--meta-->
                            </div><!--//content-->
                        </div><!--//post-inner-->
                    </article><!--//post-->
                @endforeach
            <div class="clearfix"></div>
        </div>

        <!-- PAGINATION -->
        <div class="row">
            <div class="pagination-container text-center">
                {{ $videos->links() }}
            </div>
        </div>
        <!-- PAGINATION -->

        </div>  
    </div>
</section>